# Logistic Regression

In [10]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

In [11]:
# Load dataset
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv")
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    MALE  
1         3800.0  FEMALE  
2         3250.0  FEMALE  
3            NaN     NaN  
4         3450.0  FEMALE  
..           ...     ...  
339          NaN     NaN  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE  

[344 rows x 7 columns]

In [12]:
# Drop rows containing missing values
df.dropna(inplace=True)

# Convert non-numeric data using one-hot encoding
df = pd.get_dummies(df, columns=['island', 'sex'], dtype=int)
df

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0    Adelie            39.1           18.7              181.0       3750.0   
1    Adelie            39.5           17.4              186.0       3800.0   
2    Adelie            40.3           18.0              195.0       3250.0   
4    Adelie            36.7           19.3              193.0       3450.0   
5    Adelie            39.3           20.6              190.0       3650.0   
..      ...             ...            ...                ...          ...   
338  Gentoo            47.2           13.7              214.0       4925.0   
340  Gentoo            46.8           14.3              215.0       4850.0   
341  Gentoo            50.4           15.7              222.0       5750.0   
342  Gentoo            45.2           14.8              212.0       5200.0   
343  Gentoo            49.9           16.1              213.0       5400.0   

     island_Biscoe  island_Dream  island_Torgersen  sex_FEMALE  sex_MALE  
0                0             0                 1           0         1  
1                0             0                 1           1         0  
2                0             0                 1           1         0  
4                0             0                 1           1         0  
5                0             0                 1           0         1  
..             ...           ...               ...         ...       ...  
338              1             0                 0           1         0  
340              1             0                 0           1         0  
341              1             0                 0           0         1  
342              1             0                 0           1         0  
343              1             0                 0           0         1  

[333 rows x 10 columns]

In [13]:
# Assign X and y variables
X = df.drop('species', axis=1)
y = df['species']

# Split data into test and train set and shuffle
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True)

In [14]:
# Assign algorithm
model = LogisticRegression()

# Link algorithm to X and y variables
model.fit(X_train, y_train)

C:\Users\JAVOHIR\miniconda3\envs\mohirdsai\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
# Run algorithm on test data to make predictions
y_pred = model.predict(X_test)

# Evaluate predictions
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[38  1  0]
 [ 0 22  0]
 [ 0  0 39]]

Classification Report:
               precision    recall  f1-score   support

      Adelie       1.00      0.97      0.99        39
   Chinstrap       0.96      1.00      0.98        22
      Gentoo       1.00      1.00      1.00        39

    accuracy                           0.99       100
   macro avg       0.99      0.99      0.99       100
weighted avg       0.99      0.99      0.99       100



In [16]:
# Data point to predict
penguin = [
    42,  # bill_length_mm
    18,  # bill_depth_mm
    195,  # flipper_length_mm
    4100,  # body_mass_g
    1,  # island_Biscoe
    0,  # island_Dream
    0,  # island_Torgersen
    0,  # sex_FEMALE
    1,  # sex_MALE
]
# Make prediction
model.predict([penguin])

C:\Users\JAVOHIR\miniconda3\envs\mohirdsai\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array(['Adelie'], dtype=object)